linters-settings:
  errcheck:
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    enable-all: true
  stylecheck:
    checks: ["ST1000", "ST1001"]
  nolintlint:
    require-explanation: true
    require-specific: true
  wsl:
    allow-assign-and-anything: true
    allow-cuddle-declarations: true
    allow-assign-and-call: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - goconst
    - gofmt
    - goimports
    - govet
    - mnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - wsl

run:
  issues-exit-code: 1
