version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    staticcheck:
      checks:
        - ST1000
        - ST1001
    wsl:
      allow-assign-and-call: true
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
